mycontext("[k,k]"). % at least one and at most two processes are activated

myentities([out_1,out_2,out_3,out_4,out_5,out_6,out_7,out_8]).

myenvironment("[
    k = ({act_1}.k + {act_2}.k + {act_3}.k + {act_4}.k + {act_5}.k + {act_6}.k + {act_7}.k + {act_8}.k)
    ]").

myreactions([
    react([out_1],[act_1],[out_1]),
    react([out_1,act_1],[],[req_1]),
    react([req_1],[act_1],[req_1]),
    react([req_1,lock],[],[req_1]),
    react([in_1],[act_1],[in_1]),
    react([in_1,act_1],[],[out_1,done]),
    react([req_1,act_2],[],[req_1]),
    react([req_1,act_3],[],[req_1]),
    react([req_1,act_4],[],[req_1]),
    react([req_1,act_5],[],[req_1]),
    react([req_1,act_6],[],[req_1]),
    react([req_1,act_7],[],[req_1]),
    react([req_1,act_8],[],[req_1]),
    react([req_1,act_1],[lock,act_2,act_3,act_4,act_5,act_6,act_7,act_8],[in_1,lock]),
    react([out_2],[act_2],[out_2]),
    react([out_2,act_2],[],[req_2]),
    react([req_2],[act_2],[req_2]),
    react([req_2,lock],[],[req_2]),
    react([in_2],[act_2],[in_2]),
    react([in_2,act_2],[],[out_2,done]),
    react([req_2,act_1],[],[req_2]),
    react([req_2,act_3],[],[req_2]),
    react([req_2,act_4],[],[req_2]),
    react([req_2,act_5],[],[req_2]),
    react([req_2,act_6],[],[req_2]),
    react([req_2,act_7],[],[req_2]),
    react([req_2,act_8],[],[req_2]),
    react([req_2,act_2],[lock,act_1,act_3,act_4,act_5,act_6,act_7,act_8],[in_2,lock]),
    react([out_3],[act_3],[out_3]),
    react([out_3,act_3],[],[req_3]),
    react([req_3],[act_3],[req_3]),
    react([req_3,lock],[],[req_3]),
    react([in_3],[act_3],[in_3]),
    react([in_3,act_3],[],[out_3,done]),
    react([req_3,act_1],[],[req_3]),
    react([req_3,act_2],[],[req_3]),
    react([req_3,act_4],[],[req_3]),
    react([req_3,act_5],[],[req_3]),
    react([req_3,act_6],[],[req_3]),
    react([req_3,act_7],[],[req_3]),
    react([req_3,act_8],[],[req_3]),
    react([req_3,act_3],[lock,act_1,act_2,act_4,act_5,act_6,act_7,act_8],[in_3,lock]),
    react([out_4],[act_4],[out_4]),
    react([out_4,act_4],[],[req_4]),
    react([req_4],[act_4],[req_4]),
    react([req_4,lock],[],[req_4]),
    react([in_4],[act_4],[in_4]),
    react([in_4,act_4],[],[out_4,done]),
    react([req_4,act_1],[],[req_4]),
    react([req_4,act_2],[],[req_4]),
    react([req_4,act_3],[],[req_4]),
    react([req_4,act_5],[],[req_4]),
    react([req_4,act_6],[],[req_4]),
    react([req_4,act_7],[],[req_4]),
    react([req_4,act_8],[],[req_4]),
    react([req_4,act_4],[lock,act_1,act_2,act_3,act_5,act_6,act_7,act_8],[in_4,lock]),
    react([out_5],[act_5],[out_5]),
    react([out_5,act_5],[],[req_5]),
    react([req_5],[act_5],[req_5]),
    react([req_5,lock],[],[req_5]),
    react([in_5],[act_5],[in_5]),
    react([in_5,act_5],[],[out_5,done]),
    react([req_5,act_1],[],[req_5]),
    react([req_5,act_2],[],[req_5]),
    react([req_5,act_3],[],[req_5]),
    react([req_5,act_4],[],[req_5]),
    react([req_5,act_6],[],[req_5]),
    react([req_5,act_7],[],[req_5]),
    react([req_5,act_8],[],[req_5]),
    react([req_5,act_5],[lock,act_1,act_2,act_3,act_4,act_6,act_7,act_8],[in_5,lock]),
    react([out_6],[act_6],[out_6]),
    react([out_6,act_6],[],[req_6]),
    react([req_6],[act_6],[req_6]),
    react([req_6,lock],[],[req_6]),
    react([in_6],[act_6],[in_6]),
    react([in_6,act_6],[],[out_6,done]),
    react([req_6,act_1],[],[req_6]),
    react([req_6,act_2],[],[req_6]),
    react([req_6,act_3],[],[req_6]),
    react([req_6,act_4],[],[req_6]),
    react([req_6,act_5],[],[req_6]),
    react([req_6,act_7],[],[req_6]),
    react([req_6,act_8],[],[req_6]),
    react([req_6,act_6],[lock,act_1,act_2,act_3,act_4,act_5,act_7,act_8],[in_6,lock]),
    react([out_7],[act_7],[out_7]),
    react([out_7,act_7],[],[req_7]),
    react([req_7],[act_7],[req_7]),
    react([req_7,lock],[],[req_7]),
    react([in_7],[act_7],[in_7]),
    react([in_7,act_7],[],[out_7,done]),
    react([req_7,act_1],[],[req_7]),
    react([req_7,act_2],[],[req_7]),
    react([req_7,act_3],[],[req_7]),
    react([req_7,act_4],[],[req_7]),
    react([req_7,act_5],[],[req_7]),
    react([req_7,act_6],[],[req_7]),
    react([req_7,act_8],[],[req_7]),
    react([req_7,act_7],[lock,act_1,act_2,act_3,act_4,act_5,act_6,act_8],[in_7,lock]),
    react([out_8],[act_8],[out_8]),
    react([out_8,act_8],[],[req_8]),
    react([req_8],[act_8],[req_8]),
    react([req_8,lock],[],[req_8]),
    react([in_8],[act_8],[in_8]),
    react([in_8,act_8],[],[out_8,done]),
    react([req_8,act_1],[],[req_8]),
    react([req_8,act_2],[],[req_8]),
    react([req_8,act_3],[],[req_8]),
    react([req_8,act_4],[],[req_8]),
    react([req_8,act_5],[],[req_8]),
    react([req_8,act_6],[],[req_8]),
    react([req_8,act_7],[],[req_8]),
    react([req_8,act_8],[lock,act_1,act_2,act_3,act_4,act_5,act_6,act_7],[in_8,lock]),
    react([lock],[done],[lock])
    ]).



adventities(E) :- myentities(E). % an adversary with the same entities
advreactions(Rs) :- myreactions(Rs). % an adversary with the same reactions
advcontext(K) :- mycontext(K). % an adversary with the same reactions context
myexperiment([10,10],[[a,b],[a]]).
myassert("-{c} inW").
mybhml("<-{c} inW>[-{c} inW]<-{c} inW>true").

